spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_oauth2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
  application:
    name: oauth2-server
  thymeleaf:
    cache: false